name: Build and deploy Next.js app to Azure Web App - Ssim-Next

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies (for validation)
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app (for validation)
        run: pnpm run build

      - name: Generate package-lock.json for Azure
        run: |
          echo "Generating package-lock.json for Azure npm compatibility..."
          npm install --package-lock-only
          echo "Package-lock.json generated successfully"

      - name: Prepare lightweight deployment package
        run: |
          echo "Creating lightweight deployment package for Azure building..."
          rm -f deploy.zip
          # Include source code and configs for Azure to build
          zip -r deploy.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.md" \
            -x ".next/*" \
            2>/dev/null || true
          echo "Deployment package created: $(du -h deploy.zip | cut -f1)"

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 12 # Reduced timeout since Azure builds are usually faster

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Ssim-Next"
          slot-name: "Production"
          package: deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E2F380228651460DAA19A08B90CFD7D6 }}
