name: Build and deploy Next.js app to Azure Web App - Ssim-Next

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm run build

      - name: Create production dependencies (ZERO optimization)
        run: |
          echo "Creating production installation with ZERO file modifications..."
          rm -rf node_modules

          # Use npm for Azure compatibility - DO NOT TOUCH ANYTHING ELSE
          npm install --package-lock-only
          npm ci --omit=dev --ignore-scripts

          # DO NOT DELETE, MOVE, OR MODIFY ANY FILES
          # Leave everything exactly as npm installed it

          echo "Production installation completed - NO files modified"
          echo "Package size: $(du -sh node_modules | cut -f1)"

      - name: Prepare deployment package
        run: |
          echo "Creating deployment package..."
          rm -f deploy.zip

          # Package everything with zero exclusions (except obvious cache)
          zip -9 -r deploy.zip \
            .next \
            public \
            package.json \
            node_modules \
            next.config.js \
            2>/dev/null || true

          PACKAGE_SIZE=$(du -h deploy.zip | cut -f1)
          echo "Deployment package created: $PACKAGE_SIZE"

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15 # Increased for larger package

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Ssim-Next"
          slot-name: "Production"
          package: deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E2F380228651460DAA19A08B90CFD7D6 }}
